# Generated by Django 4.2.7 on 2023-12-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'Заказ'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name_plural': 'Обработка товара'},
        ),
        migrations.AlterModelOptions(
            name='orderprocessing',
            options={'verbose_name_plural': 'Обработка заказа'},
        ),
        migrations.AddField(
            model_name='news',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='news/', verbose_name='Изображение'),
        ),
    ]
