# Generated by Django 4.2.7 on 2023-12-09 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_product_video_product_video_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='article',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Артикул товара'),
        ),
    ]
