# Generated by Django 4.2.7 on 2023-12-09 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_product_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='video_url',
        ),
        migrations.AddField(
            model_name='product',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Видеообзор товара'),
        ),
    ]
