# Generated by Django 4.2.7 on 2024-01-05 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='profile_photos/', verbose_name='Фото'),
        ),
    ]
