# Generated by Django 4.2.7 on 2024-01-08 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_order_options_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
