# Generated by Django 4.2.7 on 2024-01-08 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_order_total_price_orderproduct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderproduct',
            options={'verbose_name_plural': 'Заказ'},
        ),
    ]
