# Generated by Django 4.2.7 on 2024-01-23 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_orderproduct_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_choices',
            field=models.CharField(blank=True, choices=[('Наличными', 'Наличными'), ('Картой курьеру', 'Картой курьеру')], max_length=20, null=True, verbose_name='Форма оплаты'),
        ),
    ]
